---
name: Repository request form
description: Submit a request to create a New Repository.
title: 'add {repository} repo, using template'
assignees:
  - thejaswitricon
body:
  - type: markdown
    attributes:
      value: |
        Please provide the {Repository-name} and select the {Template-repository} name from the dropdown below.
  - type: input
    id: name
    attributes:
      label: Repository-name
      description: Name of new repository.
      placeholder: ABC
    validations:
      required: true
  - type: dropdown
    id: Template-repository
    attributes:
      label: Template-repository
      description: Template reposiotry to be used to create new repository.
      options:
        - template-repository
        - terraform-aws-template
    validations:
      required: true
