---
  name: Add Repository

  on:
    issues:
      types: [opened]

  concurrency:
    group: ${{github.ref}}-${{github.workflow}}
    cancel-in-progress: true

  permissions:
    contents: write
    issues: write
    packages: read
    pull-requests: write
    repository-projects: read
    statuses: write

  jobs:
    setup:
      name: Repository Setup
      runs-on: ubuntu-latest
      env:
        TOKEN: ${{ secrets.PAT_GITHUB }}
        REPO_OWNER: ${{ github.event.repository.owner.login }}
      if: contains(github.event.issue.labels.*.name, 'add repository')
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          id: checkout
          with:
            fetch-depth: 0

        - uses: stefanbuck/github-issue-parser@v3
          id: issue-parser
          with:
            template-path: .github/ISSUE_TEMPLATE/repository-request.yml

        - name: Create new repository
          run: |
            echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json
            ISSUE_CONTENT=$(cat issue.json)
            echo "$ISSUE_CONTENT"
            REPOSITORY_NAME=$(echo $ISSUE_CONTENT | jq -r '.name')
            TEMPLATE_REPO_NAME=$(echo $ISSUE_CONTENT | jq -r '."Template-repository"')
            CREATE_REPO=$(curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ env.REPO_OWNER }}/$TEMPLATE_REPO_NAME/generate \
              -d "{\"owner\":\"${{ env.REPO_OWNER }}\",\"name\":\"$REPOSITORY_NAME\",\"include_all_branches\":false,\"private\":false}")
