---
  name: Post Template Process

  on:
    push:
      branches: [main, test]
    workflow_dispatch:

  concurrency:
    group: ${{github.ref}}-${{github.workflow}}
    cancel-in-progress: true

  permissions:
    contents: write
    issues: write
    packages: read
    pull-requests: write
    repository-projects: read
    statuses: write

  jobs:
    setup:
      name: Repository Setup
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          id: checkout
          with:
            fetch-depth: 0

        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Get Template-repository name
          id: get-repo-name
          run: |
            REPO_INFO=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT_GITHUB }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/tandfgroup/${{ github.event.repository.name }})
            TEMPLATE_REPO_NAME=$(echo $REPO_INFO | jq -r '.template_repository.name')
            echo "REPO_NAME=${TEMPLATE_REPO_NAME}" >> $GITHUB_OUTPUT

        - name: Find and Replace
          if: ${{ steps.get-repo-name.outputs.REPO_NAME != 'null' }}
          uses: richardrigutins/replace-in-files@v2
          with:
            files: '*'
            search-text: '${{ steps.get-repo-name.outputs.REPO_NAME }}'
            replacement-text: '${{ github.event.repository.name }}'

        # - name: Remove File
        #   run: |
        #     git rm CHANGELOG.md
        #   continue-on-error: true

        - name: Push changes
          uses: stefanzweifel/git-auto-commit-action@v5

        - name: Add branch protection and collaborators
          run: |
            npm install
            node template-setup.mjs
          env:
            TOKEN: ${{ secrets.PAT_GITHUB }}
            NEW_REPO_NAME: ${{ github.event.repository.name }}
            COLLABORATORS: |
              [
                { "teams": "everything-as-code", "permission": "push" },
                { "teams": "everything-as-code-admins", "permission": "admin" },
                { "teams": "everything-as-code-squad", "permission": "maintain" },
                { "teams": "ops", "permission": "push" },
                { "teams": "owners", "permission": "admin" }
              ]

        # - name: Disable this workflow
        #   shell: bash
        #   run: |
        #     gh workflow disable "${{ github.workflow }}"
        #   env:
        #     GITHUB_TOKEN: ${{secrets.PAT_GITHUB}}
