---
  name: Create Repo from Template

  on:
    issues:
      types: [opened]

  concurrency:
    group: ${{github.ref}}-${{github.workflow}}
    cancel-in-progress: true

  permissions:
    contents: write
    issues: write
    pull-requests: write
    repository-projects: read

  jobs:
    setup:
      name: Repository Setup
      runs-on: ubuntu-latest
      env:
        GH_TOKEN: ${{ secrets.PAT_GITHUB }}
        REPO_OWNER: ${{ github.event.repository.owner.login }}
      if: ${{ github.event.issue.title == 'add {repository} repo, using template' }}
      steps:
        - run: echo "The Title of your PR is ${{ github.event.issue.title }}"
        - name: Checkout
          uses: actions/checkout@v4
          id: checkout
          with:
            fetch-depth: 0

        - name: Parse issue
          uses: stefanbuck/github-issue-parser@v3
          id: issue-parser
          with:
            template-path: .github/ISSUE_TEMPLATE/repository-request.yml

        - name: Create new repository
          id: repo-names
          run: |
            echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json
            ISSUE_CONTENT=$(cat issue.json)
            REPOSITORY_NAME=$(echo $ISSUE_CONTENT | jq -r '.name')
            TEMPLATE_REPO_NAME=$(echo $ISSUE_CONTENT | jq -r '."Template-repository"')
            echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_OUTPUT
            echo "TEMPLATE_REPO_NAME=${TEMPLATE_REPO_NAME}" >> $GITHUB_OUTPUT
          env:
            REPOSITORY_NAME: ${{ steps.repo-names.outputs.REPOSITORY_NAME }}
            TEMPLATE_REPO_NAME: ${{ steps.repo-names.outputs.TEMPLATE_REPO_NAME }}

        - name: Update issue
          uses: actions-cool/issues-helper@v3
          with:
            actions: 'update-issue'
            token: ${{ env.GH_TOKEN }}
            issue-number: ${{ github.event.issue.number }}
            state: 'open'
            title: 'chore: add  ${{ steps.repo-names.outputs.REPOSITORY_NAME }} repo, using ${{ steps.repo-names.outputs.TEMPLATE_REPO_NAME }} repo'
            update-mode: 'replace'

        #     CREATE_REPO=$(curl -L \
        #       -X POST \
        #       -H "Accept: application/vnd.github+json" \
        #       -H "Authorization: Bearer $TOKEN" \
        #       -H "X-GitHub-Api-Version: 2022-11-28" \
        #       "https://api.github.com/repos/${{ env.REPO_OWNER }}/${{ env.TEMPLATE_REPO_NAME }}/generate" \
        #       -d "{\"owner\":\"${{ env.REPO_OWNER }}\",\"name\":\"${{ env.REPOSITORY_NAME }}\",\"include_all_branches\":false,\"private\":false}")
