name: Post Template Create

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{github.ref}}-${{github.workflow}}
  cancel-in-progress: true

permissions:
  contents: write
  repository-projects: read


jobs:
  pr:
    uses: thejaswicy/reusable-workflows/.github/workflows/reusable.yml@main
    with:
      # Any required inputs for the reusable workflow
      - ".github/workflows"
    secrets:
      GH_TOKEN: ${{ secrets.PAT_GITHUB1 || secrets.GITHUB_TOKEN }}
