name: Project Specific Workflow
on:
  push:
    branches: [main]
  workflow_dispatch:
    # Defaults here are for worflow_dispatch only, all other events are set in EnvSetup.setup-output-defaults:
    inputs:
      repo-name:
        description: 'Passing the name of the caller repo to the reusable workflow'
        default: 'true'

jobs:
  EnvSetup:
    name: Pass repo name
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ steps.pass-repo-name.outputs.REPO_NAME }}
    steps:
      - name: set outputs with default values
        id: pass-repo-name
        run: |
          echo "REPO_NAME=${{ github.event.repository.name }}" >> "GITHUB_OUTPUT"
  reusable-workflow:
    needs: [EnvSetup]
    uses: thejaswicy/reusable-workflows/.github/workflows/reusable.yml@main
    with:
      repo-name: ${{needs.EnvSetup.outputs.repo-name}}
    secrets:
      TOKEN: "${{ secrets.PAT_GITHUB1 }}"
