name: Call a reusable workflow

on:
  issues:
      types: [opened, reopened]

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      issues: write
      pull-requests: read
      repository-projects: read
    uses: thejaswicy/reusable-workflows/.github/workflows/reusable.yml@main
    with:
      issue-number: ${{ github.event.issue.number }}
      repo-owner: ${{ github.event.repository.owner.login }}
    secrets:
      GH_TOKEN: ${{ secrets.PAT_GITHUB }}
