name: Post Template Create

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{github.ref}}-${{github.workflow}}
  cancel-in-progress: true

permissions:
  contents: write
  repository-projects: read

jobs:
  setup:
    name: Repository Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GH_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
      REPO_NAME: ${{ github.event.repository.name }}
      REPO_OWNER: ${{ github.event.repository.owner.login }}
      TEST_SECRET: ${{ secrets.TEST }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        id: checkout
        with:
          fetch-depth: 0

      - name: Get Template-repository name
        id: get-repo-name
        env:
          TEST_SECRET: ${{ secrets.TEST }}
        run: |
          echo "Secret= ${{env.TEST_SECRET}}"

      - name: Set up secret file
        env:
          TEST_SECRET: ${{ secrets.TEST }}
        run: |
          echo "${{secrets.TEST_SECRET}}" | sed 's/./& /g'

      - name: Set env as secret
        run: |
          import os
          for q in (os.getenv("TEST_SECRET")):
            print(q)
        shell: python

      - name: Set env as secret
        run: |
          echo "MY_CLIENT_SECRET (***)     = ${MY_CLIENT_SECRET}"
          echo "MY_CLIENT_SECRET (openssl) = $(echo "${MY_CLIENT_SECRET}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${MY_OPENSSL_ITER} -k "${MY_OPENSSL_PASSWORD}")"
          echo "Copy the above value, and then execute locally:"
          echo "echo PASTE_HERE | openssl base64 -d | openssl enc -d -pbkdf2 -iter $MY_OPENSSL_ITER -aes-256-cbc -k $MY_OPENSSL_PASSWORD"
